### ISSUE TITLE
add a book that is not present in this repo

### ISSUE THREAD

**Issue by TheAdityaGupta** [TheAdityaGupta/BOOKS#1]

**Comment by KartikRN** [comment]
I would like to add the book Ethical hacking.
please Assign it to me.

**Comment by asad0206** [comment]
I would like to add Competitive programming and Automata Books
Please assign it to me

**Comment by kb-s** [comment]
I want to add DSA book, please assign this to me

**Comment by Ankitverma3507** [comment]
Hello Sir, Can you assign this issue to me?

**Comment by CristinaEU1** [comment]
Please assign this to me too, thanks!

**Comment by pulkithanda** [comment]
Please assign this to me too and I submitted a PR regarding the same.

**Comment by lotfijb** [comment]
can you assign this to me I have a JavaScript book

**Comment by anjaligoswami** [comment]
i want to add self help book, pls assign this issue to me

**Comment by Shunux-Stuxnet** [comment]
I want to add ethical hacking books, assign me that.
