### ISSUE TITLE
Spelling error in readme file

### ISSUE THREAD

**Issue by anjaligoswami** [TheAdityaGupta/BOOKS#100]
![image](https://user-images.githubusercontent.com/75528719/198073793-6d79238f-5975-4b8a-b571-8c883a99bc5b.png)

I want to fix this issue, please assign this issue. I have already corrected it. I just want to get assigned and make a pull request.

**Comment by anjaligoswami** [comment]
@TheAdityaGupta

**Comment by TheAdityaGupta** [comment]
Not a helpful issue for the repo
