### ISSUE TITLE
Add a docker cheat sheet.

### ISSUE THREAD

**Issue by Dhruvil-Lakhtaria** [TheAdityaGupta/BOOKS#103]
Can add a docker cheat sheet under the cheatsheet directory.

**Comment by TheAdityaGupta** [comment]
There is already a docker cheatsheet.
Check if you have something different

**Comment by Dhruvil-Lakhtaria** [comment]
I will add few more things and snippets on top of existing one.

**Comment by TheAdityaGupta** [comment]
Ok

**Comment by kelvinparmar** [comment]
Should I add this docker cheat sheet?

**Comment by TheAdityaGupta** [comment]
@kelvinparmar no 
There's already one cheatsheet.
That's enough

**Comment by Dhruvil-Lakhtaria** [comment]
Added few updates in docker cheat sheet and made a pr
