### ISSUE TITLE
Add a Linux cheat sheet 

### ISSUE THREAD

**Issue by kelvinparmar** [TheAdityaGupta/BOOKS#108]

**Comment by kelvinparmar** [comment]
Should I add this?

**Comment by TheAdityaGupta** [comment]
Ok

**Comment by TheAdityaGupta** [comment]
Also move the GitHub cheatsheet from Linux folder to cheatsheets

**Comment by kelvinparmar** [comment]
I am not understand  please explain me what are you want ?

**Comment by TheAdityaGupta** [comment]
Add your Linux cheatsheet
Then from the Linux folder download then delete a file named github-git cheatsheet, 
Then upload it to cheatsheets folder

**Comment by kelvinparmar** [comment]
Where I have to upload my linux cheetsheat ? 
And what are you saying about github-git cheetsheat? 
I am not understood
