### ISSUE TITLE
Add more self help books

### ISSUE THREAD

**Issue by jha-om** [TheAdityaGupta/BOOKS#136]
@TheAdityaGupta Hey, can I add some more self help books?
Can you assign this an issue number and also one question that I need to understand this how these pdf files are being uploaded into the respective folder.

Also if this issue get merged will this as a valid pr for hacktoberfest2023?

**Comment by TheAdityaGupta** [comment]
go to the desired folder and select add files via upload.
if u have to upload file greater than 25mb u will have to clone it and yes ofc its a valid pr
