### ISSUE TITLE
 css cheat sheet

### ISSUE THREAD

**Issue by Ashasindhu** [TheAdityaGupta/BOOKS#80]
Want to add css cheat sheet .Please assign this to me for this hactoberfest

**Comment by Ashasindhu** [comment]
I am facing an issue with cloning the project .You can kindly assign this issue to someone else

**Comment by TheAdityaGupta** [comment]
No need to clone it.
Just star and fork the repo , add file in appropriate folder with suitable title via upload
@Ashasindhu

**Comment by TheAdityaGupta** [comment]
A css cheatsheet is already present in the repo .
Add something new
