### ISSUE TITLE
Adding new book to Interview Prep folder

### ISSUE THREAD

**Issue by alabador** [TheAdityaGupta/BOOKS#83]
Hello, I would like to add a new book to the Interview Prep folder.

**Comment by RadhikaChhabra17** [comment]
Hello, I have added 2 books
1. Cracking the coding interview to the Interview Preperation folder
2. Guide to Competitive Programming to the Competitive Programming Folder
Kindly review my PR #91

**Comment by alabador** [comment]
I also added a book (Elements of Programming Interviews) in the Interview Prep folder. 
Please check #92 when available, thanks.
